version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: finance-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 54321
      POSTGRES_DB: financeapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
